
-- HABILITAR RLS EM TODAS AS TABELAS (sem isso GRANT libera geral)

ALTER TABLE public.assinante ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qualidade_resolucao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plano ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico_assinatura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_cobranca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fatura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispositivo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classificacao_maturidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.genero ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profissional ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visualizacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obra_genero ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obra_profissional ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episodio ENABLE ROW LEVEL SECURITY;